# Site settings
title: bolo
email: zakkeener@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Advanced boxing training.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: bolo
github_username:  bolo

# Build settings
markdown: kramdown
